# Generated by Django 3.2.6 on 2022-02-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='note',
            new_name='note_content',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='title',
            new_name='note_title',
        ),
    ]
